#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
#include "hitechnic-irseeker-v2.h";

int testencodera = 0;
int testencoderb = 0;
task main()
{
	nMotorEncoder[motorArm] = 0;
	nMotorEncoder[motorB] = 0;
	int irval1 = -1;
	int irval2 = -1;
	int dummy = -1;
	int rotOrigin = 0;
	int rotCurrent = 0;
	rotOrigin = nMotorEncoder[motorArm];
	int targetRot = nMotorEncoder[motorB];
	int rotRelative = 0;
	int threshold = 200;
	servo[servo1] = 230;
	servo[servo2] = 202;

	while(1)
	{
		//testencodera = nMotorEncoder[motorArm];
		//testencoderb = nMotorEncoder[motorB]*5;
		rotCurrent = nMotorEncoder[motorArm];
		targetRot = nMotorEncoder[motorB]*5;
		rotRelative = rotCurrent-targetRot;

		HTIRS2readEnhanced(S2,irval1,dummy);
		HTIRS2readEnhanced(S3,irval2,dummy);

		if(externalBattery == -1)
		{
				nMotorEncoder[motorArm] = 0;
				nMotorEncoder[motorB] = 0;
				motor[motorArm] = 0;
		}

		if(rotRelative > threshold)
		{
			motor[motorArm] = -60;
		}
		else
		{
			if(rotRelative < -threshold)
			{
				motor[motorArm] = 25;
			}
			else
			{
				motor[motorArm] = 0;
			}
		}

		if(SensorValue[S4] == 1)
  	{
  		servo[servo2] = 160;
  		servo[servo1] = 230;
  	}
  	else
  	{
  		servo[servo2] = 202;//open tube (drop ball)
  		servo[servo1] = 165;
  	}

		nxtDisplayTextLine(0, "Arm Adjust%s", "");
		nxtDisplayTextLine(1, "Eencoder = %i", nMotorEncoder[motorArm]);
		nxtDisplayTextLine(2, "tet batt = %i", externalBattery);
		nxtDisplayTextLine(3, "nxt batt = %i", nImmediateBatteryLevel);
		nxtDisplayTextLine(4, "irval1 = %i", irval1);
		nxtDisplayTextLine(5, "irval2 = %i", irval2);
	}
}
