#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ,               sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h";
#include "JoystickDriver.c"
int AUTMOTPOW = 25;
//int AUTMOTPOW = 90;


void setArm(float target)
{
	while((nMotorEncoder[motorArm]) < target)
	{
		motor[motorArm] = 90;
	}
	while((nMotorEncoder[motorArm]) > target)
	{
		motor[motorArm] = -90;
	}
	motor[motorArm] = 0;
}
void setArm(float target, int power)
{
	while((nMotorEncoder[motorArm]) < target)
	{
		motor[motorArm] = power;
	}
	while((nMotorEncoder[motorArm]) > target)
	{
		motor[motorArm] = -power;
	}
	motor[motorArm] = 0;
}

void dropBall()
{
	servo[servo2] = 202;
}
void closeBall()
{
	servo[servo2] = 160;
}
void dropBallWiggle(int freq, int total)
{
	time1[timer2] = 0;
	while(time1[timer2] < total)
	{
		dropBall();
		time1[timer3] = 0;
		while(time1[timer3] < freq/2  && time1[timer2] < total)
		{

		}
		closeBall();
		time1[timer3] = 0;
		while(time1[timer3] < freq/2  && time1[timer2] < total)
		{

		}
	}
}

void stopMotors()
{
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
}
void stopAllTime(int time)
{
		stopMotors();
		wait1Msec(time);
}

void turnLeftEncoder(float clicks)
{
	motor[motorRight] = 0;
	motor[motorLeft] = AUTMOTPOW;
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks)
	{
		//do nohing
	}
	stopMotors();
}

void turnRightEncoder(float clicks)
{
	motor[motorRight] = 0;
	motor[motorLeft] = -AUTMOTPOW;
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks)
	{
		//do nohing
	}
	stopMotors();
}

void turnRightEncoder(float clicks, int time)
{
	motor[motorRight] = 0;
	motor[motorLeft] = -AUTMOTPOW;
	time1[T1]= 0;
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks && time1[T1] < time)
	{
		//do nohing
	}
	stopMotors();
}

void turnRightBackEncoder(float clicks, int time) //Robbie was here
{
	motor[motorRight] = 0;
	motor[motorLeft] = AUTMOTPOW;
	time1[T1]= 0;
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks && time1[T1] < time)
	{
		//do nohing
	}
	stopMotors();
}
void turnLeftBackEncoder(float clicks, int time)
{
	motor[motorRight] = -AUTMOTPOW;
	motor[motorLeft] = 0;
	time1[T1]= 0;
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks && time1[T1] < time)
	{
		//do nohing
	}
	stopMotors();
}

void moveForward()
{
	motor[motorLeft] = -AUTMOTPOW;
	motor[motorRight] = AUTMOTPOW;
}

void moveBackward()
{
	motor[motorLeft] = AUTMOTPOW;
	motor[motorRight] = -AUTMOTPOW;
}

void moveForwardEncoder(float clicks)
{
	moveForward();
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks)
	{
		//do nohing
	}
	stopMotors();
}
void moveForwardEncoder(float clicks, int time)
{
	moveForward();
	time1[T1]= 0;
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks && time1[T1] < time)
	{
		//do nohing
	}
	stopMotors();
}

void moveBackwardEncoder(float clicks)
{
	moveBackward();
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks)
	{
		//do nohing
	}
	stopMotors();
}
void moveBackwardEncoder(float clicks, int time)
{
	moveBackward();
	time1[T1]= 0;
	nMotorEncoder[motorLeft] = 0;
	while(abs(nMotorEncoder[motorLeft]) < clicks && time1[T1] < time)
	{
		//do nohing
	}
	stopMotors();
}

/////////////////////////////////////////////////////////////////////////////////////////




task main()
{
	nxtDisplayTextLine(0, "Floor Autonomous%s", "");
	waitForStart();
	int direction = 0;
	int direction2 = 0;
	int strength = 0;
	int strength2 = 0;
	string phase = "movingToBlueLine";
	int irPosition = -1;
	bool running = true;
	HTIRS2readEnhanced(S2,direction,strength);
	HTIRS2readEnhanced(S3,direction2,strength2);
	//irPosition = direction;
	nMotorEncoder[motorArm] = 0;
	//motor[motorA] = 100;
	servo[servo1] = 230;
	servo[servo2] = 160;
	setArm(-1850);
	//irPosition = 3;


	if(direction == 0)
	{
		irPosition = 3;
	}
	else
	{
		if(direction2 == 3)
		{
			irPosition = 1;
		}
		else
		{
			irPosition = 2;
		}
	}

	while(running)
	{
		//HTIRS2readEnhanced(S2,direction,strength);

		if(phase == "movingToBlueLine")
		{
			//AUTMOTPOW = 30;
			//moveForwardEncoder(2685);
			//moveForwardEncoder(2600);
			//stopAllTime(250);
			//phase = "getInPosition";
			//if(irPosition != 0 && irPosition != 3 && irPosition != 4)
			//if(irPosition == 0)
			{
				//HTIRS2readEnhanced(S2,direction,strength);
				//switch(direction)
				//{
					//case 0:
						//irPosition = 0;break;

					//case 2:
						//irPosition = 5;//break;

					//case 3:
						//irPosition = 4;break;

					//default: break;
				//}
			}
			phase = "getInPosition";
		}
		else if(phase == "getInPosition")
		{
			switch(irPosition)
			{
				case 1:
					setArm(-12532);
					stopAllTime(500);
					moveForwardEncoder(6825,5000);
					stopAllTime(1500);
					dropBallWiggle(200,2500);
					stopAllTime(500);
					break;

				case 2:
					AUTMOTPOW = 30;
					//AUTMOTPOW = 90;
					moveForwardEncoder(4227);
					stopAllTime(250);
					turnLeftEncoder(2321);
					stopAllTime(500);
					setArm(-12532,100);
					stopAllTime(500);
					//moveForwardEncoder(2174);//too less
					//moveForwardEncoder(2100);//too far now
					//moveForwardEncoder(1750);//little more than this
					//moveForwardEncoder(1850);//too much
					moveForwardEncoder(1850);
					stopAllTime(500);
					//turnRightEncoder(3666);//little too less in testing
					//turnRightEncoder(3800);//too little
					//turnRightEncoder(3900);
					turnRightEncoder(4100);
					stopAllTime(500);
					moveForwardEncoder(1250,2000);
					stopAllTime(500);
					dropBallWiggle(200,2500);
					stopAllTime(500);
					break;

				case 3:
					AUTMOTPOW = 40;
					//AUTMOTPOW = 90;
					moveForwardEncoder(4202);
					stopAllTime(400);
					turnLeftEncoder(2317);//encoder might not be reset
					stopAllTime(250);
					//moveForwardEncoder(6107);//too far
					//moveForwardEncoder(5500);//to far now
					//moveForwardEncoder(5250);//still to far : 50 less
					moveForwardEncoder(5200);
					stopAllTime(400);
					//turnRightEncoder(1984);//too little in testing
					turnRightEncoder(2500);
					stopAllTime(250);
					moveForwardEncoder(100);
					stopAllTime(400);
					setArm(-12532);
					stopAllTime(250);
					//turnRightEncoder(3946);//too little now
					turnRightEncoder(3800);
					stopAllTime(250);
					//moveForwardEncoder(1326, 2500);//going to be too much
					//moveForwardEncoder(1000, 1000);//too less in testing
					moveForwardEncoder(2500, 1000);
					stopAllTime(400);
					dropBallWiggle(200,2500);
					stopAllTime(250);
					break;

				default:
					break;
			}
			running = false;
		}
	}
	AUTMOTPOW = 25;
	moveBackwardEncoder(500);
	stopAllTime(500);
	AUTMOTPOW = 40;
	//turnRightBackEncoder(8300,5000);//too much in anders' opinion
	turnRightBackEncoder(7700,5000);
	stopAllTime(500);
	AUTMOTPOW = 100;
	moveBackwardEncoder(4000,1000);
	stopAllTime(250);
	turnLeftBackEncoder(2000,1000);
	stopAllTime(250);
	moveBackwardEncoder(750);
	stopAllTime(500);
	//turnRightEncoder(4443);
	//stopAllTime(500);
	//setArm(-1850);
	//stopAllTime(500);
	/*
	moveForwardEncoder(2411);
	stopAllTime(500);
	turnLeftEncoder(1265);
	stopAllTime(500);
	AUTMOTPOW = 100;
	moveForwardEncoder(6065,3000);
	stopAllTime(250);
	turnRightEncoder(1500,500);
	stopAllTime(250);
	*/

	//while(1)
	{
		//nxtDisplayTextLine(0, "irPosition = %i", irPosition);
	}

	//setArm(-2000,70);
	//setArm(0,20);
}
