#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorArm,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-irseeker-v2.h";


float mapsquare(float input)
{
	float new = 0;
	if(input >= 0)
	{
		new = (pow(((100.0*input)/127.0)/100.0,2.0)*100.0);
	}
	else
	{
		new = (pow(((100.0*input)/127.0)/100.0,2.0)*-100.0);
	}
	return 	new;
}


task main()
{
	int threshold = 20;
	int motorDpower = 0;
	int motorGpower = 0;
	int direction = -1;
	int tophat = -1;
	int tophat2 = -1;
	string driveState = "normal";
	bool sixIsPressed = false;
	bool sixWasPressed = false;
	bool tenHasBeenPressed = false;
	bool robotIsMoving = false;

	int joyy1 = 0;
	int joyx2 = 0;
	int motorDencoder = 0;
	int motorArmencoder = 0;
	//one rotation is 1440
	nMotorEncoder[motorArm] = 0;
	motor[motorArm] = 0;

	servo[servo1] = 230;
	servo[servo2] = 202;

	int servo2position = 202;

	while(1)
	{
		sixWasPressed = sixIsPressed;
		getJoystickSettings(joystick);
		//getJoystickSettings(joystick2);

		if(joy1Btn(6))
		{
				sixIsPressed = true;
		}
		else
		{
				sixIsPressed = false;
		}

		if(driveState == "normal")
		{
			joyy1 = joystick.joy1_y1;
			joyx2 = joystick.joy1_x2;
		}
		else
		{
			joyy1 = -joystick.joy1_y1;
			joyx2 = joystick.joy1_x2;
		}
		tophat = joystick.joy1_TopHat;
		//tophat2 = joystick.joy2_TopHat;

		if(abs(joyy1) < threshold)
		{
			joyy1 = 0;
		}
		else
		{
			joyy1 = (int)mapsquare(joyy1);
		}

		if(abs(joyx2) < threshold)
		{
			joyx2 = 0;
		}
		else
		{
			if(joyy1==0)
			{
				joyx2 = (int)(mapsquare(joyx2)*0.5);
			}
			else
			{
				joyx2 = (int)(mapsquare(joyx2));
			}
		}

		motorDpower = (-1*joyy1)-joyx2;
		motorGpower = (1*joyy1)-joyx2;

		if(joy1Btn(5))
		{
			motorDpower = motorDpower/2.5;
			motorGpower = motorGpower/2.5;
		}

		motor[motorD] = motorDpower;
		motor[motorG] = motorGpower;
		if(motorDpower != 0 || motorGpower != 0)
		{
			robotIsMoving = true;
		}
		else
		{
			robotIsMoving = false;
		}

		motorDencoder = nMotorEncoder[motorD];
		motorArmencoder = nMotorEncoder[motorArm];

  	if(tophat == -1)
  	{
  		if(tenHasBeenPressed)
  		{
  			tophat = tophat2;
  		}
  	}

  	if(tophat != -1 && !robotIsMoving)
  	{
  		switch(tophat)
  		{
  			case 0:
  				motor[motorArm] = -90;
  				break;

  			case 4:
  				motor[motorArm] = 90;
  				break;

  			default:
  				break;
  		}
  	}
  	else
  	{
  		motor[motorArm] = 0;
  	}

  	if(joy1Btn(2))
  	{
  		servo[servo1] = 155;
  	}
  	else
  	{
  		if(joy1Btn(4))
  		{
  			servo[servo1] = 230;
  		}
  		else
  		{
  			if(joy1Btn(3))
	  		{
	  			servo[servo1] = 165;
	  		}
  		}
  	}


  	if(!joy1Btn(8) && !joy1Btn(7))
  	{
  			//if(joy2Btn(8))
  			{
  			    //servo2position = 160;
  		  }
  		  //else
  		  {
  		      //if(joy2Btn(7))
  		      {
  		          //servo2position = 195;
  		      }
  		  }
  	}
  	if(joy1Btn(8))
  	{
  		servo2position = 160;
  	}
  	else
  	{
  		if(joy1Btn(7))
  		{
  			servo2position = 202;
  		}
  	}
  	servo[servo2] = servo2position;

  	if(joy1Btn(11))
  	{
  		nMotorEncoder[motorD] = 0;
  		nMotorEncoder[motorE] = 0;
  	}

  	if(sixIsPressed && !sixWasPressed)
  	{
  		if(driveState == "normal")
  		{
  			driveState = "weird peter";
  		}
  		else
  		{
  			driveState = "normal";
  		}
  	}
  	//if(joy2Btn(10))
  	{
  		tenHasBeenPressed = true;
  	}

  	nxtDisplayTextLine(1, "servo2 = %i", servo[servo2]);
  	nxtDisplayTextLine(2, "Dencoder = %i", motorDencoder);
  	nxtDisplayTextLine(3, "Aencoder = %i", motorArmencoder);
  	nxtDisplayTextLine(4, "irval = %i", direction);
  	nxtDisplayTextLine(5, "state = %s", driveState);
	}
}
